### ISSUE TITLE
Hallucinations and unresponsiveness

### ISSUE THREAD

**Issue by esanmar** [upstash/degree-guru#5]
After doing several crawls of the same website, the answers are not exact at all. I have tried changing models but I have not achieved good results. 

But, no results. Thanks!

**Comment by CahidArda** [comment]
Hi there,

Thank you for trying out our tool!

Firstly, I'm unable to check the repository you shared. It seems to be either deleted or set to private. Could you please make it public?

There are a few things we can check to find the issue:

1. Check the crawler logs to ensure the website is being crawled correctly. The crawler should print out every URL it visited.
2. Check the vector store through the [Upstash Console](https://console.upstash.com/) and see if the vectors are stored as expected. You can use the Data Browser under your vector store.
3. Check if you need to update [your agent template](https://github.com/upstash/degree-guru/blob/master/src/app/api/guru/route.tsx#L114) and [initial message](https://github.com/upstash/degree-guru/blob/master/src/app/page.tsx#L27). We configured these for Stanford and you may need to change it according to your website.
4. Which models have you experimented with? If you've tried different embedding models, ensure that you've updated the embedding model settings in both the crawler and the chatbot.

**Comment by esanmar** [comment]
Solved. Thanks!

**Comment by CahidArda** [comment]
Glad to hear that!
